markdown: kramdown
exclude: ['README.md', 'LICENSE']
incremental: true

name: Wenchen's blog
description:  objective -> happiness, dataset->life experience,model->brain, optimization_algorithm->SGD 
url: 'http://wenchenli.github.io'
baseurl: ""
github: 'WenchenLi'
gaaccount: 'UA-61762966-1'
comments: true
disqus: 'wenchenli'
permalink: /:year/:month/:title
paginate: 3
highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate','jekyll-responsive-image']
exclude: ['README.md', 'LICENSE']